name: Build and Deploy Spring Boot App with Docker

on:
  push:
    branches:
      - main  # or change to your main branch name

env:
  IMAGE_NAME: springboot-app-docker-image

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          
     # - name: Run Docker Container
      #  run: |
     #    docker run -d --name springboot-app \
     #      -e SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
     #       -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
     #      -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
     #       -p 8200:8200 \
     #      ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
     #      printenv
     
      - name: Check the DB URL value (GitHub Action level)
        run: |
         echo "SPRING_DATASOURCE_URL=${{ vars.DB_URL }}"

      - name: Run Docker Container and print env var
        run: |
          docker run --rm \
          -e SPRING_DATASOURCE_URL=jdbc:oracle:thin:@localhost:1521:ORCL \
          -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
          -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
          ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
          sh -c 'echo "SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL"'


